sudo: required
service:
  - docker

before_install:
  - docker build -t vijaykumar23/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vijaykumar23/react-test npm test

after_success:
  - docker build -t vijaykumar23/multi-client ./client
  - docker build -t vijaykumar23/multi-nginx ./nginx
  - docker build -t vijaykumar23/multi-server ./server
  - docker build -t vijaykumar23/multi-worker ./worker
  # Login into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push vijaykumar23/multi-client
  - docker push vijaykumar23/multi-nginx
  - docker push vijaykumar23/multi-server
  - docker push vijaykumar23/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-105155065346'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY